### ISSUE TITLE
Deploy submariner broker with rancher fqdn cluster

### ISSUE THREAD

**Issue by Negashev** [submariner-io/submariner#11]
Use Rancher 2.2.1 and submariner [helm](https://github.com/rancher/submariner-charts)

- Generate pem for `broker.submariner.MY-DOMIAN.COM` (openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 3650 -out submariner.pem)
- Create cluster (broker) with fqdn `broker.submariner.MY-DOMIAN.COM`  ( 10.42.0.0/16, 10.43.0.0/16 )
- Set dns `broker.submariner.MY-DOMIAN.COM` A row to nodes from cluster (broker)
- Install submariner broker to cluster (broker) form helm
- Get ca.crt and data.token (from kubectl)
- Create cluster (cluser 1) ( 10.50.0.0/16, 10.60.0.0/16, cluster1.local )
- Install submariner to cluster (cluser 1) form helm with `Broker Server` = `broker.submariner.MY-DOMIAN.COM:6443`, ca.crt and data.token
- Got error
```
I0329 07:31:52.430872 1 shared_informer.go:123] caches populated
I0329 07:31:52.431140 1 datastoresyncer.go:78] Ensuring we are the only endpoint active for this cluster
I0329 07:31:52.431705 1 shared_informer.go:123] caches populated
I0329 07:31:52.431739 1 tunnel.go:64] Starting workers
I0329 07:31:52.431789 1 tunnel.go:67] Started workers
F0329 07:31:52.807627 1 datastoresyncer.go:81] Error while retrieving endpoints Get https://broker.submariner.MY-DOMIAN.COM:6443/apis/submariner.io/v1/namespaces/submariner-k8s-broker/endpoints: x509: certificate is valid for broker-submariner-0, broker-submariner-1, localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not broker.submariner.MY-DOMIAN.COM
goroutine 37 [running]:
github.com/rancher/submariner/vendor/k8s.io/klog.stacks(0xc000290500, 0xc00021c000, 0x1c5, 0x4ed)
/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:828 +0xd4
github.com/rancher/submariner/vendor/k8s.io/klog.(*loggingT).output(0x1df5a60, 0xc000000003, 0xc0001108f0, 0x1d874a7, 0x12, 0x51, 0x0)
/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:779 +0x306
github.com/rancher/submariner/vendor/k8s.io/klog.(*loggingT).printf(0x1df5a60, 0x3, 0x125f2a6, 0x23, 0xc0004ebac8, 0x1, 0x1)
/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:678 +0x14b
github.com/rancher/submariner/vendor/k8s.io/klog.Fatalf(0x125f2a6, 0x23, 0xc0004ebac8, 0x1, 0x1)
/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:1207 +0x67
github.com/rancher/submariner/pkg/controllers/datastoresyncer.(*DatastoreSyncer).ensureExclusiveEndpoint(0xc0003ea540)
/go/src/github.com/rancher/submariner/pkg/controllers/datastoresyncer/datastoresyncer.go:81 +0x968
github.com/rancher/submariner/pkg/controllers/datastoresyncer.(*DatastoreSyncer).Run(0xc0003ea540, 0xc00008a6c0, 0x0, 0x0)
/go/src/github.com/rancher/submariner/pkg/controllers/datastoresyncer/datastoresyncer.go:139 +0x2af
main.main.func1.3(0xc000411410, 0xc0003ea540, 0xc00008a6c0, 0xc000273d30)
/go/src/github.com/rancher/submariner/main.go:132 +0x63
created by main.main.func1
/go/src/github.com/rancher/submariner/main.go:130 +0xb63
00[DMN] signal of type SIGHUP received. Reloading configuration
```

**Comment by Negashev** [comment]
Sweet hack 🗡 

work when i add service with name `kubernetes` on submariner and set `Broker Server`=kubernetes:6443

```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  namespace: submariner
spec:
  externalName: broker.submariner.MY-DOMIAN.COM
  ports:
  - name: default
    port: 6443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ExternalName
```
