### ISSUE TITLE
submariner endpoint loss connection

### ISSUE THREAD

**Issue by buhe** [submariner-io/submariner#125]
I setup a three DC submariner cluster before 9 days.

Today, I found 3 DC loss Pod-to-Pod connection.

At broker 

kubectl logs -f submariner-84c5b445db-4wp2f -n submariner

```
I0731 14:35:54.502386       1 leaderelection.go:249] failed to renew lease submariner/submariner-engine-lock: failed to tryAcquireOrRenew context deadline exceeded
F0731 14:35:54.502446       1 main.go:178] leaderelection lost
goroutine 1 [running]:
github.com/rancher/submariner/vendor/k8s.io/klog.stacks(0xc000266500, 0xc00036c1c0, 0x3f, 0x1ae)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:828 +0xd4
github.com/rancher/submariner/vendor/k8s.io/klog.(*loggingT).output(0x1df5a60, 0xc000000003, 0xc00062e000, 0x1d80e12, 0x7, 0xb2, 0x0)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:779 +0x306
github.com/rancher/submariner/vendor/k8s.io/klog.(*loggingT).printf(0x1df5a60, 0x3, 0x125080b, 0x13, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:678 +0x14b
github.com/rancher/submariner/vendor/k8s.io/klog.Fatalf(0x125080b, 0x13, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/klog/klog.go:1207 +0x67
main.startLeaderElection.func1()
	/go/src/github.com/rancher/submariner/main.go:178 +0x47
github.com/rancher/submariner/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc0003a0000)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:163 +0x40
github.com/rancher/submariner/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0003a0000, 0x13ccfc0, 0xc000246cc0)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:172 +0x112
github.com/rancher/submariner/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x13cd000, 0xc000042048, 0x13d24e0, 0xc000350480, 0x37e11d600, 0x2540be400, 0xb2d05e00, 0xc0000f9bd0, 0x12c7660, 0x0, ...)
	/go/src/github.com/rancher/submariner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:184 +0x99
main.startLeaderElection(0x13eee60, 0xc000350360, 0x13cd500, 0xc0002db4c0, 0xc0000f9bd0)
	/go/src/github.com/rancher/submariner/main.go:170 +0x27c
main.main()
	/go/src/github.com/rancher/submariner/main.go:147 +0x580
I0731 14:35:55.601931       1 main.go:142] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"submariner", Name:"submariner-engine-lock", UID:"da65ab31-ad2d-11e9-bff9-02c47c506f46", APIVersion:"v1", ResourceVersion:"1221170", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ip-172-31-23-192.cn-north-1.compute.internal-submariner-engine stopped leading
```

And other DC log is :

kubectl logs submariner-84f57c45ff-wszbj -n submariner
```
07[NET] sending packet: from 172.16.152.62[500] to 52.83.57.176[500] (500 bytes)
I0802 04:05:51.256740       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 04:05:51.258058       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 04:05:51.261961       1 datastoresyncer.go:194] Attempting to trigger an update of the central datastore with the updated CRD
I0802 04:05:51.263240       1 tunnel.go:87] Processing endpoint object: submariner/nx-submariner-cable-nx-172-31-44-229
I0802 04:05:51.266810       1 datastoresyncer.go:236] The updated endpoint object was not for this cluster, skipping updating the datastore
I0802 04:05:51.266813       1 ipsec.go:169] Installing cable submariner-cable-nx-172-31-44-229
I0802 04:05:51.267849       1 ipsec.go:453] Found existing connection: submariner-cable-nx-172-31-44-229
I0802 04:05:51.267890       1 tunnel.go:109] endpoint processed by tunnel controller
I0802 04:05:51.267901       1 tunnel.go:87] Processing endpoint object: submariner/bj-submariner-cable-bj-172-31-23-192
I0802 04:05:51.268940       1 datastoresyncer.go:236] The updated endpoint object was not for this cluster, skipping updating the datastore
I0802 04:05:51.269919       1 ipsec.go:169] Installing cable submariner-cable-bj-172-31-23-192
I0802 04:05:51.270953       1 ipsec.go:453] Found existing connection: submariner-cable-bj-172-31-23-192
I0802 04:05:51.270990       1 tunnel.go:109] endpoint processed by tunnel controller
I0802 04:05:51.271000       1 tunnel.go:87] Processing endpoint object: submariner/hz-submariner-cable-hz-172-16-152-62
I0802 04:05:51.271023       1 datastoresyncer.go:249] Attempting to trigger an update of the central datastore with the updated endpoint CRD
I0802 04:05:51.273005       1 ipsec.go:162] Not installing cable for local cluster
I0802 04:05:51.273016       1 tunnel.go:109] endpoint processed by tunnel controller
I0802 04:05:51.294774       1 kubernetes.go:331] Cluster CRD matched what we received from k8s broker, not reconciling
I0802 04:05:51.294787       1 datastoresyncer.go:196] Update of cluster in central datastore was successful
I0802 04:05:51.303146       1 kubernetes.go:370] Endpoint CRD matched what we received from k8s broker, not reconciling
I0802 04:05:51.303157       1 datastoresyncer.go:254] Update of endpoint in central datastore was successful
I0802 04:05:51.327783       1 reflector.go:357] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: Watch close - *v1.Cluster total 0 items received
I0802 04:05:53.777818       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 04:05:53.780462       1 datastoresyncer.go:300] Cluster CRD matched what we received from datastore, not reconciling
I0802 04:05:53.782590       1 datastoresyncer.go:300] Cluster CRD matched what we received from datastore, not reconciling
I0802 04:05:53.784691       1 datastoresyncer.go:300] Cluster CRD matched what we received from datastore, not reconciling
I0802 04:05:53.792637       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 04:05:53.794852       1 datastoresyncer.go:415] Endpoint CRD matched what we received from datastore, not reconciling
I0802 04:05:53.796762       1 datastoresyncer.go:415] Endpoint CRD matched what we received from datastore, not reconciling
I0802 04:05:53.799036       1 datastoresyncer.go:415] Endpoint CRD matched what we received from datastore, not reconciling
```

Thanks, buhe@netless

**Comment by buhe** [comment]
kubectl logs submariner-routeagent-72gp5 -n submariner

```
I0802 05:19:23.526445       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 05:19:23.526517       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {bj-submariner-cable-bj-172-31-23-192  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/bj-submariner-cable-bj-172-31-23-192 dba3e227-ad2d-11e9-bff9-02c47c506f46 12579 1 2019-07-23 09:40:08 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {bj submariner-cable-bj-172-31-23-192 ip-172-31-23-192.cn-north-1.compute.internal [10.73.0.0/16 10.72.0.0/16] 172.31.23.192 52.80.228.238 true ipsec map[]}}
I0802 05:19:23.526574       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {hz-submariner-cable-hz-172-16-152-62  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/hz-submariner-cable-hz-172-16-152-62 03493753-ad30-11e9-bff9-02c47c506f46 14170 1 2019-07-23 09:55:33 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {hz submariner-cable-hz-172-16-152-62 k8s-test-1-4 [10.43.0.0/16 10.42.0.0/16] 172.16.152.62 118.31.5.150 true ipsec map[]}}
I0802 05:19:23.526611       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {nx-submariner-cable-nx-172-31-44-229  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/nx-submariner-cable-nx-172-31-44-229 92cfa04b-ad2e-11e9-bff9-02c47c506f46 13102 1 2019-07-23 09:45:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {nx submariner-cable-nx-172-31-44-229 ip-172-31-44-229.cn-northwest-1.compute.internal [10.63.0.0/16 10.62.0.0/16] 172.31.44.229 52.83.57.176 true ipsec map[]}}
I0802 05:19:23.526680       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 05:19:23.526712       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {hz  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/hz 0348a5d1-ad30-11e9-bff9-02c47c506f46 14169 1 2019-07-23 09:55:33 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {hz [blue] [10.43.0.0/16] [10.42.0.0/16]}}
I0802 05:19:23.526745       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {nx  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/nx 92cf0c4a-ad2e-11e9-bff9-02c47c506f46 13101 1 2019-07-23 09:45:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {nx [blue] [10.63.0.0/16] [10.62.0.0/16]}}
I0802 05:19:23.526765       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {bj  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/bj dba2e53b-ad2d-11e9-bff9-02c47c506f46 12578 1 2019-07-23 09:40:08 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {bj [blue] [10.73.0.0/16] [10.72.0.0/16]}}
I0802 05:19:23.531913       1 route.go:134] Processing cluster object: submariner/hz
I0802 05:19:23.533856       1 route.go:155] cluster processed by route controller
I0802 05:19:23.533870       1 route.go:134] Processing cluster object: submariner/nx
I0802 05:19:23.535221       1 route.go:155] cluster processed by route controller
I0802 05:19:53.526669       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 05:19:53.526737       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {bj-submariner-cable-bj-172-31-23-192  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/bj-submariner-cable-bj-172-31-23-192 dba3e227-ad2d-11e9-bff9-02c47c506f46 12579 1 2019-07-23 09:40:08 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {bj submariner-cable-bj-172-31-23-192 ip-172-31-23-192.cn-north-1.compute.internal [10.73.0.0/16 10.72.0.0/16] 172.31.23.192 52.80.228.238 true ipsec map[]}}
I0802 05:19:53.526795       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {hz-submariner-cable-hz-172-16-152-62  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/hz-submariner-cable-hz-172-16-152-62 03493753-ad30-11e9-bff9-02c47c506f46 14170 1 2019-07-23 09:55:33 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {hz submariner-cable-hz-172-16-152-62 k8s-test-1-4 [10.43.0.0/16 10.42.0.0/16] 172.16.152.62 118.31.5.150 true ipsec map[]}}
I0802 05:19:53.526838       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {nx-submariner-cable-nx-172-31-44-229  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/nx-submariner-cable-nx-172-31-44-229 92cfa04b-ad2e-11e9-bff9-02c47c506f46 13102 1 2019-07-23 09:45:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {nx submariner-cable-nx-172-31-44-229 ip-172-31-44-229.cn-northwest-1.compute.internal [10.63.0.0/16 10.62.0.0/16] 172.31.44.229 52.83.57.176 true ipsec map[]}}
I0802 05:19:53.526896       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 05:19:53.526925       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {hz  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/hz 0348a5d1-ad30-11e9-bff9-02c47c506f46 14169 1 2019-07-23 09:55:33 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {hz [blue] [10.43.0.0/16] [10.42.0.0/16]}}
I0802 05:19:53.526950       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {nx  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/nx 92cf0c4a-ad2e-11e9-bff9-02c47c506f46 13101 1 2019-07-23 09:45:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {nx [blue] [10.63.0.0/16] [10.62.0.0/16]}}
I0802 05:19:53.526976       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {bj  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/bj dba2e53b-ad2d-11e9-bff9-02c47c506f46 12578 1 2019-07-23 09:40:08 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {bj [blue] [10.73.0.0/16] [10.72.0.0/16]}}
I0802 05:19:53.532123       1 route.go:134] Processing cluster object: submariner/hz
I0802 05:19:53.534245       1 route.go:155] cluster processed by route controller
I0802 05:19:53.534267       1 route.go:134] Processing cluster object: submariner/nx
I0802 05:19:53.535765       1 route.go:155] cluster processed by route controller
I0802 05:20:23.526909       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 05:20:23.526997       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {bj-submariner-cable-bj-172-31-23-192  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/bj-submariner-cable-bj-172-31-23-192 dba3e227-ad2d-11e9-bff9-02c47c506f46 12579 1 2019-07-23 09:40:08 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {bj submariner-cable-bj-172-31-23-192 ip-172-31-23-192.cn-north-1.compute.internal [10.73.0.0/16 10.72.0.0/16] 172.31.23.192 52.80.228.238 true ipsec map[]}}
I0802 05:20:23.527102       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {hz-submariner-cable-hz-172-16-152-62  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/hz-submariner-cable-hz-172-16-152-62 03493753-ad30-11e9-bff9-02c47c506f46 14170 1 2019-07-23 09:55:33 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {hz submariner-cable-hz-172-16-152-62 k8s-test-1-4 [10.43.0.0/16 10.42.0.0/16] 172.16.152.62 118.31.5.150 true ipsec map[]}}
I0802 05:20:23.527130       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {nx-submariner-cable-nx-172-31-44-229  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/nx-submariner-cable-nx-172-31-44-229 92cfa04b-ad2e-11e9-bff9-02c47c506f46 13102 1 2019-07-23 09:45:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {nx submariner-cable-nx-172-31-44-229 ip-172-31-44-229.cn-northwest-1.compute.internal [10.63.0.0/16 10.62.0.0/16] 172.31.44.229 52.83.57.176 true ipsec map[]}}
I0802 05:20:23.527205       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 05:20:23.527236       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {nx  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/nx 92cf0c4a-ad2e-11e9-bff9-02c47c506f46 13101 1 2019-07-23 09:45:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {nx [blue] [10.63.0.0/16] [10.62.0.0/16]}}
I0802 05:20:23.527280       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {bj  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/bj dba2e53b-ad2d-11e9-bff9-02c47c506f46 12578 1 2019-07-23 09:40:08 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {bj [blue] [10.73.0.0/16] [10.72.0.0/16]}}
I0802 05:20:23.527307       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {hz  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/hz 0348a5d1-ad30-11e9-bff9-02c47c506f46 14169 1 2019-07-23 09:55:33 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {hz [blue] [10.43.0.0/16] [10.42.0.0/16]}}
I0802 05:20:23.532464       1 route.go:134] Processing cluster object: submariner/nx
I0802 05:20:23.534726       1 route.go:155] cluster processed by route controller
I0802 05:20:23.534746       1 route.go:134] Processing cluster object: submariner/hz
I0802 05:20:23.536180       1 route.go:155] cluster processed by route controller
I0802 05:20:40.762438       1 reflector.go:357] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: Watch close - *v1.Endpoint total 0 items received
I0802 05:20:53.527155       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 05:20:53.527233       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {hz-submariner-cable-hz-172-16-152-62  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/hz-submariner-cable-hz-172-16-152-62 03493753-ad30-11e9-bff9-02c47c506f46 14170 1 2019-07-23 09:55:33 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {hz submariner-cable-hz-172-16-152-62 k8s-test-1-4 [10.43.0.0/16 10.42.0.0/16] 172.16.152.62 118.31.5.150 true ipsec map[]}}
I0802 05:20:53.527299       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {nx-submariner-cable-nx-172-31-44-229  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/nx-submariner-cable-nx-172-31-44-229 92cfa04b-ad2e-11e9-bff9-02c47c506f46 13102 1 2019-07-23 09:45:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {nx submariner-cable-nx-172-31-44-229 ip-172-31-44-229.cn-northwest-1.compute.internal [10.63.0.0/16 10.62.0.0/16] 172.31.44.229 52.83.57.176 true ipsec map[]}}
I0802 05:20:53.527326       1 route.go:247] Enqueueing endpoint for route controller &{{Endpoint submariner.io/v1} {bj-submariner-cable-bj-172-31-23-192  submariner /apis/submariner.io/v1/namespaces/submariner/endpoints/bj-submariner-cable-bj-172-31-23-192 dba3e227-ad2d-11e9-bff9-02c47c506f46 12579 1 2019-07-23 09:40:08 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {bj submariner-cable-bj-172-31-23-192 ip-172-31-23-192.cn-north-1.compute.internal [10.73.0.0/16 10.72.0.0/16] 172.31.23.192 52.80.228.238 true ipsec map[]}}
I0802 05:20:53.527505       1 reflector.go:215] github.com/rancher/submariner/pkg/client/informers/externalversions/factory.go:117: forcing resync
I0802 05:20:53.527545       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {hz  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/hz 0348a5d1-ad30-11e9-bff9-02c47c506f46 14169 1 2019-07-23 09:55:33 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {hz [blue] [10.43.0.0/16] [10.42.0.0/16]}}
I0802 05:20:53.527588       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {nx  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/nx 92cf0c4a-ad2e-11e9-bff9-02c47c506f46 13101 1 2019-07-23 09:45:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {nx [blue] [10.63.0.0/16] [10.62.0.0/16]}}
I0802 05:20:53.527621       1 route.go:236] Enqueueing cluster for route controller &{{Cluster submariner.io/v1} {bj  submariner /apis/submariner.io/v1/namespaces/submariner/clusters/bj dba2e53b-ad2d-11e9-bff9-02c47c506f46 12578 1 2019-07-23 09:40:08 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {bj [blue] [10.73.0.0/16] [10.72.0.0/16]}}
I0802 05:20:53.532776       1 route.go:134] Processing cluster object: submariner/hz
I0802 05:20:53.535074       1 route.go:155] cluster processed by route controller
I0802 05:20:53.535116       1 route.go:134] Processing cluster object: submariner/nx
I0802 05:20:53.536543       1 route.go:155] cluster processed by route controller
```

**Comment by buhe** [comment]
maybe forgot disable source/dest checking
