### ISSUE TITLE
"ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.

### ISSUE THREAD

**Issue by mikekuzak** [submariner-io/submariner#1922]
Hi,

We are running 2 Rancher RKE clusters v1.20.12 and I tried to use submariner (v0.13-cr0), to federate the clusters. I have different CIDs as advised. After installing the broker and connecting the 2 clusters the Canal plugin started crash-looping 

![image](https://user-images.githubusercontent.com/18675587/178306912-e33ddd05-54bb-4327-9090-cf293cd5d753.png)

 with the following error: 
```
goroutine 141 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000136180, 0xc000889710, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x6a5
github.com/sirupsen/logrus.(*Entry).Panic(0xc00013f360, 0xc000a29bb8, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0xfa
github.com/projectcalico/felix/ipsets.(*IPSets).ApplyUpdates(0xc0004fbc20)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201221195443-7b3bfe7a5d7b/ipsets/ipsets.go:342 +0x359
github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func1(0xc0000e9b80, 0xc0009ed124, 0xc0004fbc20)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201221195443-7b3bfe7a5d7b/dataplane/linux/int_dataplane.go:1610 +0x2f
created by github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201221195443-7b3bfe7a5d7b/dataplane/linux/int_dataplane.go:1609 +0x41e
2022-07-04 13:19:31.680 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.681 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:31.684 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.684 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:31.689 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.689 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:31.694 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.694 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:31.704 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.704 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:31.722 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.722 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:31.756 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.756 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:31.822 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.822 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:31.951 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:31.952 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:32.210 [ERROR][489400] felix/ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2022-07-04 13:19:32.210 [WARNING][489400] felix/ipsets.go 309: Failed to resync with dataplane error=exit status 1 family="inet"
2022-07-04 13:19:32.708 [WARNING][489400] felix/health.go 188: Reporter is not ready. name="int_dataplane"
2022-07-04 13:19:32.724 [ERROR][489400] felix/ipsets.go 916: Failed to read IP sets error=exit status 1 family="inet"
2022-07-04 13:19:32.724 [PANIC][489400] felix/ipsets.go 342: Failed to update IP sets after multiple retries. family="inet"
panic: (*logrus.Entry) 0xc000cf4320
goroutine 324 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0001121e0, 0xc0005d5da0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x6a5
github.com/sirupsen/logrus.(*Entry).Panic(0xc0000cd3b0, 0xc000adbbb8, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0xfa
github.com/projectcalico/felix/ipsets.(*IPSets).ApplyUpdates(0xc00018f680)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201221195443-7b3bfe7a5d7b/ipsets/ipsets.go:342 +0x359
github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func1(0xc000614c00, 0xc000ba0164, 0xc00018f680)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201221195443-7b3bfe7a5d7b/dataplane/linux/int_dataplane.go:1610 +0x2f
created by github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20201221195443-7b3bfe7a5d7b/dataplane/linux/int_dataplane.go:1609 +0x41e
```

The underlying hosts are Flatcar Linux (3139.2.3) with ipset V7.11 on them. 

Is there a compatibility issue between the host machine and the containers ? That would be bad as this tries the container to the underlying OS. 

Thanks for any advise.

**Comment by dfarrell07** [comment]
Thanks for the report! We should look into this, but we don't have active devs who can easily deploy this K8s distro. We're collecting similar issues and looking for help in better supporting K3s.

**Comment by dfarrell07** [comment]
We're still looking for folks to contribute to K3s support. +Let's go ahead and close this, we can re-open if someone is able to work on it.
