### ISSUE TITLE
Deploying Submariner: Invalid value: 0x0: must be specified for an update

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#242]
[Deploying Submariner - must be specified for an update.txt](https://github.com/submariner-io/submariner/files/3917754/Deploying.Submariner.-.must.be.specified.for.an.update.txt)

```
[nmanos@nmanos submariner-operator]$ kubconf_a  subctl join --clusterid subm-cluster-a ./broker-info.subm --ikeport 501 --nattport 4501
* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
* There are 1 labeled nodes in the cluster:
  - ip-10-0-71-116.ec2.internal
* Deploying the submariner operator
* The operator is up and running
* Discovering network details
    Discovered network details:
        Network plugin:  OpenShift
        ClusterIP CIDRs: [172.30.0.0/16]
        Pod CIDRs:       [10.128.0.0/14]
* Deploying Submariner
panic: submariners.submariner.io "submariner" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/operator/deploy.Ensure(0xc00000a3c0, 0x15366db, 0x5, 0x1546b40, 0x12, 0x1195, 0x1f5, 0x0, 0xc0002fc8c0, 0x40, ...)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/operator/deploy/ensure.go:51 +0x6d9
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.joinSubmarinerCluster(0xc0004ccf20)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:137 +0x33e
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.glob..func2(0x23c9040, 0xc0004d6b60, 0x1, 0x7)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:69 +0x14a
github.com/spf13/cobra.(*Command).execute(0x23c9040, 0xc0004d6af0, 0x7, 0x7, 0x23c9040, 0xc0004d6af0)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x23c92c0, 0x1252269, 0xc00066df88, 0xc00003e118)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:864
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:36
main.main()
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:6 +0x2f

```

pod log attached.

**Comment by tpantelis** [comment]
This should be filed in the submariner-operator repo. The `Ensure` function tries to do a replace update but k8s does a CAS with ResourceVersion so you must do a get first and merge with the existing object. We should be able to use the [CreateOrUpdate](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L136) helper.

**Comment by tpantelis** [comment]
> This should be filed in the submariner-operator repo. The `Ensure` function tries to do a replace update but k8s does a CAS with ResourceVersion so you must do a get first and merge with the existing object. We should be able to use the [CreateOrUpdate](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L136) helper.

Actually we just need to call `Create` and check for `IsAlreadyExists` since we don't need to update the object.

**Comment by tpantelis** [comment]
This is fixed in submariner-operator.
