### ISSUE TITLE
Submariner fails to install "route and agent" on k3s

### ISSUE THREAD

**Issue by c0dyhi11** [submariner-io/submariner#367]
Hello,

I'm new to submariner and I'm trying to get it working with k3s. I have followed the prereqs and made sure I have unique CIDRs for pods and services as well as a unique DNS suffix.

The broker installs just fine against my first (Single node) k3s cluster. But when I try and deploy the route and agent, I get the following error:

```bash
$ subctl join --kubeconfig us-west-2 broker-info.subm --disable-nat
* broker-info.subm says broker is at: https://147.75.109.169:6443
? What is your cluster ID? us-west-2
* No available node, skipping labeling
 ✓ Deploying the Submariner operator 
* Discovering network details
? What's the ClusterIP service CIDR for your cluster? 172.16.128.0/17
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e9dcc3]

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.getPodCIDR(0x0, 0x0, 0x0, 0x0, 0xf, 0x0, 0x0)
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:214 +0x1c3
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.joinSubmarinerCluster(0xc00054e000, 0xc00030fce0)
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:185 +0x274
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.glob..func2(0x308e5c0, 0xc0002e1ec0, 0x1, 0x4)
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:98 +0x214
github.com/spf13/cobra.(*Command).execute(0x308e5c0, 0xc0002e1e80, 0x4, 0x4, 0x308e5c0, 0xc0002e1e80)
        /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x308e840, 0x1ea1c80, 0xc000673f88, 0xc0000aa058)
        /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:864
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:55
main.main()
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:22 +0x2f
```
This is k3s `v1.17.2+k3s1` that is being installed as follows:
```bash
CLUSTER_CIDR='172.31.0.0/17'
SERVICE_CIDR='172.16.128.0/17'
K3S_VER='v1.17.2+k3s1'
HOSTNAME='us-west-2'

curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$K3S_VER INSTALL_K3S_EXEC="server --no-deploy traefik --cluster-cidr $CLUSTER_CIDR --service-cidr $SERVICE_CIDR --cluster-domain $HOSTNAME.local" sh
```
I'm installing nginx instead of traefik. 

Any help would be great! Thanks!

**Comment by tpantelis** [comment]
"No available node, skipping labeling" means there's no worker node to label as the gateway, ie there's only the one master node and subctl does not label the master node as k8s disallows scheduling of user workloads on the master.  I suspect the subsequent panic was related to that. You can add the `submariner.io/gateway=true` label manually

**Comment by c0dyhi11** [comment]
> "No available node, skipping labeling" means there's no worker node to label as the gateway, ie there's only the one master node and subctl does not label the master node as k8s disallows scheduling of user workloads on the master. I suspect the subsequent panic was related to that. You can add the `submariner.io/gateway=true` label manually

Thanks @tpantelis, 

But it looks like labeling these nodes seems to get past that one warning. But I'm still getting the same TRACE:

```bash
 subctl join --kubeconfig us-west-2 broker-info.subm --disable-nat
* broker-info.subm says broker is at: https://147.75.109.169:6443
? What is your cluster ID? us-west-2
* There are 1 labeled nodes in the cluster:
  - us-west-2
 ✓ Deploying the Submariner operator 
* Discovering network details
? What's the ClusterIP service CIDR for your cluster? 172.16.128.0/17
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e9dcc3]

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.getPodCIDR(0x0, 0x0, 0x0, 0x0, 0xf, 0x0, 0x0)
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:214 +0x1c3
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.joinSubmarinerCluster(0xc0002aef00, 0xc000408030)
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:185 +0x274
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.glob..func2(0x308e5c0, 0xc000516d80, 0x1, 0x4)
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:98 +0x214
github.com/spf13/cobra.(*Command).execute(0x308e5c0, 0xc000516d40, 0x4, 0x4, 0x308e5c0, 0xc000516d40)
        /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x308e840, 0x1ea1c80, 0xc0006b9f88, 0xc0000aa058)
        /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:864
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:55
main.main()
        /go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:22 +0x2f
```

**Comment by tpantelis** [comment]
The panic emanated from join.go - it wasn't able to determine the Pod CIDR dynamically and blew up before it could prompt for it:

```
func getPodCIDR(clusterCIDR string, nd *network.ClusterNetwork) (string, error) {
	if clusterCIDR != "" {
		...
		return clusterCIDR, nil
	} else if len(nd.PodCIDRs) > 0 {  ---> line 214
		return nd.PodCIDRs[0], nil
	} else {
		return askForCIDR("Pod")
	}
}
```

So  L214 needs to check for `nd != nil` as `getServiceCIDR` does so it prompts.

To work around it for now you can pass _--servicecidr_ on the command line.

**Comment by c0dyhi11** [comment]
Thanks @tpantelis,
`--servicecidr` alone wasn't enough. I had to pass `--clustercidr` as well.
```bash
subctl join --kubeconfig us-west-2 broker-info.subm --disable-nat --servicecidr=172.16.128.0/17 --clustercidr=172.16.0.0/17
```
This did the trick!
Thanks again!

**Comment by tpantelis** [comment]
Sorry I meant `--clustercidr` - it correctly prompted for the `servicecidr` already.

Reopening for tracking as we need to fix the panic.

**Comment by tpantelis** [comment]
PR: https://github.com/submariner-io/submariner-operator/pull/198
