### ISSUE TITLE
Error running ipamController: cluster does not seem to use kube-proxy goroutine

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#458]
As part of #391, I'm testing Overlapping CIDRs with globalnet option, between AWS public cluster (also the broker), and OSP private cluster.

AWS has OCP Version: 4.2.0 (Kubernetes Version: v1.14.6+2e5ed54)
OSP has OCP Version: 4.3.1 (Kubernetes Version: v1.16.2)

```
### Testing Service-Discovery: Nginx service will be identified by Domain name: nginx-cl-b ###
 [/home/nmanos/automation/ocp-install]
export KUBECONFIG=/home/nmanos/automation/ocp-install/ocpup/.config/cl1/auth/kubeconfig
/home/nmanos/automation/ocp-install/oc create deployment nginx-cl-b --image=nginx
deployment.apps/nginx-cl-b created
/home/nmanos/automation/ocp-install/oc expose deployment nginx-cl-b --port=80 --name=nginx-cl-b
service/nginx-cl-b exposed
export KUBECONFIG=/home/nmanos/automation/ocp-install/nmanos-cluster-a/auth/kubeconfig
oc run --attach=true --restart=Never --timeout=30s --rm -i --tty --generator=run-pod/v1 netshoot-cl-a --image nicolaka/netshoot -- curl --max-time 20 --verbose nginx-cl-b
* Could not resolve host: nginx-cl-b
* Closing connection 0
curl: (6) Could not resolve host: nginx-cl-b


[nmanos@nmanos ocp-install]$ oc logs submariner-globalnet-njnhm -n submariner-operator
+ trap 'exit 1' SIGTERM SIGINT
+ '[' '' == true ']'
+ DEBUG=-v=4
+ for f in iptables-save iptables
++ find_iptables_on_host iptables-save
++ chroot /host test -x /usr/sbin/iptables-save
++ echo /usr/sbin
++ return
iptables-save is present on the host at /usr/sbin/iptables-save
+ location=/usr/sbin
+ '[' /usr/sbin '!=' unknown ']'
+ echo 'iptables-save is present on the host at /usr/sbin/iptables-save'
+ sed 's!@@PATH@@!/usr/sbin!' /usr/sbin/iptables-wrapper.in
+ for f in iptables-save iptables
++ find_iptables_on_host iptables
++ chroot /host test -x /usr/sbin/iptables
++ echo /usr/sbin
++ return
+ location=/usr/sbin
+ '[' /usr/sbin '!=' unknown ']'
+ echo 'iptables is present on the host at /usr/sbin/iptables'
iptables is present on the host at /usr/sbin/iptables
+ sed 's!@@PATH@@!/usr/sbin!' /usr/sbin/iptables-wrapper.in
+ exec submariner-globalnet -v=4 -alsologtostderr
I0319 12:53:50.618313       1 main.go:31] Starting submariner-globalnet{nmanos-cluster-a-tunnel [submariner kube-system operators] submariner-operator}
W0319 12:53:50.618741       1 client_config.go:551] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0319 12:53:50.625279       1 gatewaymonitor.go:79] Starting GatewayMonitor to monitor the active Gateway node in the cluster.
I0319 12:53:50.625300       1 gatewaymonitor.go:81] Waiting for informer caches to sync
I0319 12:53:50.625440       1 reflector.go:122] Starting reflector *v1.Endpoint (30s) from github.com/submariner-io/submariner/pkg/client/informers/externalversions/factory.go:117
I0319 12:53:50.625481       1 reflector.go:160] Listing and watching *v1.Endpoint from github.com/submariner-io/submariner/pkg/client/informers/externalversions/factory.go:117
I0319 12:53:50.634352       1 gatewaymonitor.go:196] Enqueueing endpoint in gatewayMonitor {"kind":"Endpoint","apiVersion":"submariner.io/v1","metadata":{"name":"nmanos-cluster-b-tunnel-submariner-cable-nmanos-cluster-b-tunnel-10-166-0-13","namespace":"submariner-operator","selfLink":"/apis/submariner.io/v1/namespaces/submariner-operator/endpoints/nmanos-cluster-b-tunnel-submariner-cable-nmanos-cluster-b-tunnel-10-166-0-13","uid":"51346d3d-968e-4191-a878-43b614b9cc95","resourceVersion":"86175","generation":1,"creationTimestamp":"2020-03-19T10:57:58Z"},"spec":{"cluster_id":"nmanos-cluster-b-tunnel","cable_name":"submariner-cable-nmanos-cluster-b-tunnel-10-166-0-13","hostname":"nmanos-cl1-7jtkw-worker-46swj","subnets":["169.254.32.0/19"],"private_ip":"10.166.0.13","public_ip":"66.187.233.202","nat_enabled":true,"backend":"strongswan"}}
I0319 12:53:50.634699       1 gatewaymonitor.go:196] Enqueueing endpoint in gatewayMonitor {"kind":"Endpoint","apiVersion":"submariner.io/v1","metadata":{"name":"nmanos-cluster-a-tunnel-submariner-cable-nmanos-cluster-a-tunnel-10-166-38-251","namespace":"submariner-operator","selfLink":"/apis/submariner.io/v1/namespaces/submariner-operator/endpoints/nmanos-cluster-a-tunnel-submariner-cable-nmanos-cluster-a-tunnel-10-166-38-251","uid":"8516a257-013f-45ff-b920-ce463127cea2","resourceVersion":"85456","generation":1,"creationTimestamp":"2020-03-19T10:56:00Z"},"spec":{"cluster_id":"nmanos-cluster-a-tunnel","cable_name":"submariner-cable-nmanos-cluster-a-tunnel-10-166-38-251","hostname":"ip-10-166-38-251","subnets":["169.254.0.0/19"],"private_ip":"10.166.38.251","public_ip":"3.17.205.22","nat_enabled":true,"backend":"strongswan"}}
I0319 12:53:50.725535       1 shared_informer.go:123] caches populated
I0319 12:53:50.725560       1 globalnet.go:108] Install/ensure SUBMARINER-GN-MARK chain exists
I0319 12:53:50.743421       1 gatewaymonitor.go:90] Starting endpoint worker.
I0319 12:53:50.747533       1 gatewaymonitor.go:123] Endpoint nmanos-cl1-7jtkw-worker-46swj belongs to a remote cluster
I0319 12:53:50.747551       1 globalnet_egress.go:31] Marking traffic destined to remote cluster: -d 169.254.32.0/19 -j MARK --set-mark 0xC0000/0xC0000
I0319 12:53:50.759664       1 gatewaymonitor.go:138] We are now on GatewayNode 10.166.38.251
I0319 12:53:50.763476       1 gatewaymonitor.go:149] GlobalCidr configured in nmanos-cluster-a-tunnel is [169.254.0.0/19]
I0319 12:53:50.763505       1 gatewaymonitor.go:247] On Gateway Node, initializing ipamController.
I0319 12:53:50.769693       1 ipam.go:47] Setting up event handlers
I0319 12:53:50.769759       1 gatewaymonitor.go:262] Successfully initialized ipamController.
I0319 12:53:50.769864       1 ipam.go:74] Starting IPAM Controller
I0319 12:53:50.769952       1 reflector.go:122] Starting reflector *v1.Pod (1m0s) from k8s.io/client-go/informers/factory.go:132
I0319 12:53:50.769969       1 reflector.go:160] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:132
I0319 12:53:50.770267       1 reflector.go:122] Starting reflector *v1.Service (1m0s) from k8s.io/client-go/informers/factory.go:132
I0319 12:53:50.770287       1 reflector.go:160] Listing and watching *v1.Service from k8s.io/client-go/informers/factory.go:132
I0319 12:53:50.779753       1 ipam.go:195] Enqueueing openshift-console/console for ipam controller
I0319 12:53:50.779952       1 ipam.go:195] Enqueueing openshift-monitoring/alertmanager-operated for ipam controller
I0319 12:53:50.779972       1 ipam.go:195] Enqueueing openshift-operator-lifecycle-manager/v1-packages-operators-coreos-com for ipam controller
I0319 12:53:50.779988       1 ipam.go:195] Enqueueing openshift-marketplace/marketplace-operator-metrics for ipam controller
I0319 12:53:50.780002       1 ipam.go:195] Enqueueing openshift-monitoring/alertmanager-main for ipam controller
I0319 12:53:50.780018       1 ipam.go:195] Enqueueing openshift-monitoring/node-exporter for ipam controller
I0319 12:53:50.780032       1 ipam.go:195] Enqueueing openshift-authentication/oauth-openshift for ipam controller
I0319 12:53:50.780047       1 ipam.go:195] Enqueueing openshift-insights/metrics for ipam controller
I0319 12:53:50.780111       1 ipam.go:195] Enqueueing openshift-marketplace/certified-operators for ipam controller
I0319 12:53:50.780136       1 ipam.go:195] Enqueueing openshift-image-registry/image-registry-operator for ipam controller
I0319 12:53:50.780152       1 ipam.go:195] Enqueueing openshift-ingress-operator/metrics for ipam controller
I0319 12:53:50.780173       1 ipam.go:195] Enqueueing openshift-sdn/sdn for ipam controller
I0319 12:53:50.780189       1 ipam.go:195] Enqueueing openshift-etcd/host-etcd for ipam controller
I0319 12:53:50.780206       1 ipam.go:195] Enqueueing openshift-monitoring/cluster-monitoring-operator for ipam controller
I0319 12:53:50.780226       1 ipam.go:195] Enqueueing openshift-monitoring/kube-state-metrics for ipam controller
I0319 12:53:50.780265       1 ipam.go:195] Enqueueing openshift-multus/multus-admission-controller-monitor-service for ipam controller
I0319 12:53:50.780281       1 ipam.go:195] Enqueueing kubefed-operator/kubefed-operator for ipam controller
I0319 12:53:50.780297       1 ipam.go:195] Enqueueing default/openshift for ipam controller
I0319 12:53:50.780311       1 ipam.go:195] Enqueueing openshift-controller-manager/controller-manager for ipam controller
I0319 12:53:50.780326       1 ipam.go:195] Enqueueing openshift-etcd/etcd for ipam controller
I0319 12:53:50.780340       1 ipam.go:195] Enqueueing openshift-authentication-operator/metrics for ipam controller
I0319 12:53:50.780355       1 ipam.go:195] Enqueueing openshift-image-registry/image-registry for ipam controller
I0319 12:53:50.780369       1 ipam.go:195] Enqueueing submariner-operator/submariner-operator-metrics for ipam controller
I0319 12:53:50.780384       1 ipam.go:195] Enqueueing openshift-apiserver-operator/metrics for ipam controller
I0319 12:53:50.780398       1 ipam.go:195] Enqueueing openshift-monitoring/grafana for ipam controller
I0319 12:53:50.780413       1 ipam.go:195] Enqueueing openshift-monitoring/prometheus-adapter for ipam controller
I0319 12:53:50.780427       1 ipam.go:195] Enqueueing openshift-kube-apiserver-operator/metrics for ipam controller
I0319 12:53:50.780445       1 ipam.go:195] Enqueueing openshift-monitoring/openshift-state-metrics for ipam controller
I0319 12:53:50.780461       1 ipam.go:195] Enqueueing openshift-operator-lifecycle-manager/catalog-operator-metrics for ipam controller
I0319 12:53:50.780477       1 ipam.go:195] Enqueueing openshift-monitoring/prometheus-k8s for ipam controller
I0319 12:53:50.780491       1 ipam.go:195] Enqueueing openshift-kube-controller-manager-operator/metrics for ipam controller
I0319 12:53:50.780507       1 ipam.go:195] Enqueueing openshift-machine-api/cluster-autoscaler-operator for ipam controller
I0319 12:53:50.780520       1 ipam.go:195] Enqueueing openshift-marketplace/community-operators for ipam controller
I0319 12:53:50.780536       1 ipam.go:195] Enqueueing openshift-operator-lifecycle-manager/olm-operator-metrics for ipam controller
I0319 12:53:50.780550       1 ipam.go:195] Enqueueing openshift-ingress/router-default for ipam controller
I0319 12:53:50.780565       1 ipam.go:195] Enqueueing openshift-kube-apiserver/apiserver for ipam controller
I0319 12:53:50.780579       1 ipam.go:195] Enqueueing openshift-monitoring/telemeter-client for ipam controller
I0319 12:53:50.780594       1 ipam.go:195] Enqueueing openshift-console-operator/metrics for ipam controller
I0319 12:53:50.780608       1 ipam.go:195] Enqueueing openshift-ingress/router-internal-default for ipam controller
I0319 12:53:50.780625       1 ipam.go:195] Enqueueing openshift-marketplace/redhat-operators for ipam controller
I0319 12:53:50.780639       1 ipam.go:195] Enqueueing openshift-monitoring/thanos-querier for ipam controller
I0319 12:53:50.780655       1 ipam.go:195] Enqueueing openshift-monitoring/prometheus-operated for ipam controller
I0319 12:53:50.780669       1 ipam.go:195] Enqueueing openshift-apiserver/api for ipam controller
I0319 12:53:50.780706       1 ipam.go:195] Enqueueing openshift-cloud-credential-operator/cco-metrics for ipam controller
I0319 12:53:50.780722       1 ipam.go:195] Enqueueing openshift-cloud-credential-operator/controller-manager-service for ipam controller
I0319 12:53:50.780737       1 ipam.go:195] Enqueueing openshift-kube-scheduler-operator/metrics for ipam controller
I0319 12:53:50.780751       1 ipam.go:195] Enqueueing openshift-service-catalog-apiserver-operator/metrics for ipam controller
I0319 12:53:50.780767       1 ipam.go:195] Enqueueing openshift-cluster-machine-approver/machine-approver for ipam controller
I0319 12:53:50.780781       1 ipam.go:195] Enqueueing openshift-cluster-samples-operator/metrics for ipam controller
I0319 12:53:50.780796       1 ipam.go:195] Enqueueing openshift-kube-controller-manager/kube-controller-manager for ipam controller
I0319 12:53:50.780811       1 ipam.go:195] Enqueueing openshift-service-catalog-controller-manager-operator/metrics for ipam controller
I0319 12:53:50.780827       1 ipam.go:195] Enqueueing openshift-cluster-version/cluster-version-operator for ipam controller
I0319 12:53:50.780842       1 ipam.go:195] Enqueueing openshift-console/downloads for ipam controller
I0319 12:53:50.780860       1 ipam.go:195] Enqueueing openshift-dns/dns-default for ipam controller
I0319 12:53:50.780878       1 ipam.go:195] Enqueueing openshift-kube-scheduler/scheduler for ipam controller
I0319 12:53:50.780894       1 ipam.go:195] Enqueueing openshift-machine-api/machine-api-operator for ipam controller
I0319 12:53:50.780910       1 ipam.go:195] Enqueueing openshift-machine-config-operator/machine-config-daemon for ipam controller
I0319 12:53:50.780925       1 ipam.go:195] Enqueueing openshift-monitoring/prometheus-operator for ipam controller
I0319 12:53:50.780940       1 ipam.go:195] Enqueueing default/kubernetes for ipam controller
I0319 12:53:50.780954       1 ipam.go:195] Enqueueing openshift-controller-manager-operator/metrics for ipam controller
I0319 12:53:50.780970       1 ipam.go:195] Enqueueing openshift-dns-operator/metrics for ipam controller
I0319 12:53:50.780983       1 ipam.go:195] Enqueueing openshift-multus/multus-admission-controller for ipam controller
F0319 12:53:50.783668       1 gatewaymonitor.go:257] Error running ipamController: cluster does not seem to use kube-proxy
goroutine 52 [running]:
k8s.io/klog.stacks(0xc000246400, 0xc000308000, 0x7b, 0x181)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:828 +0xb1
k8s.io/klog.(*loggingT).output(0x1d86da0, 0xc000000003, 0xc00044c230, 0x1d13143, 0x11, 0x101, 0x0)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:779 +0x2d9
k8s.io/klog.(*loggingT).printf(0x1d86da0, 0x3, 0x1231d54, 0x20, 0xc00041dfa8, 0x1, 0x1)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:678 +0x14e
k8s.io/klog.Fatalf(...)
	/go/src/github.com/submariner-io/submariner/vendor/k8s.io/klog/klog.go:1207
github.com/submariner-io/submariner/pkg/globalnet/controllers/ipam.(*GatewayMonitor).initializeIpamController.func1(0xc00007fe00, 0xc0003102a0, 0xc00020c430)
	/go/src/github.com/submariner-io/submariner/pkg/globalnet/controllers/ipam/gatewaymonitor.go:257 +0xf9
created by github.com/submariner-io/submariner/pkg/globalnet/controllers/ipam.(*GatewayMonitor).initializeIpamController
	/go/src/github.com/submariner-io/submariner/pkg/globalnet/controllers/ipam/gatewaymonitor.go:255 +0x2d7

```

kube-system only runs on the private cluster (OSP) which is not the broker cluster:

```
[nmanos@nmanos ocp-install]$ kubconf_a
[nmanos@nmanos ocp-install]$ oc get pods -A | grep kube-system
[nmanos@nmanos ocp-install]$ kubconf_b
[nmanos@nmanos ocp-install]$ oc get pods -A | grep kube-system
kube-system                                             tiller-deploy-5b6b797f84-zrmq4                                    1/1     Running            32         23d
```

And kube-proxy does not run on any cluster at all:

```

[nmanos@nmanos ocp-install]$ kubconf_a
[nmanos@nmanos ocp-install]$ oc get pods -A | grep kube-proxy
[nmanos@nmanos ocp-install]$ kubconf_b
[nmanos@nmanos ocp-install]$ oc get pods -A | grep kube-proxy
[nmanos@nmanos ocp-install]$ 

```

**Comment by sridhargaddam** [comment]
A workaround to this issue is implemented via the following PR - https://github.com/submariner-io/submariner/pull/459

In a future PR we would re-enable kubeproxy validation in some generic way.

**Comment by manosnoam** [comment]
Just for the record, the #463 fix, does not fix Globalnet with Service-Discovery when deploying on private cluster with Overlapping CIDRs:
```

[2020-03-23 13:52:57]
 ### Testing GlobalNet: Nginx service will be identified its Global IP ###
 [/home/nmanos/automation/ocp-install]

kubconf_b
export KUBECONFIG=/home/nmanos/automation/ocp-install/ocpup/.config/cl1/auth/kubeconfig
global_ip=169.254.38.215
kubconf_a
export KUBECONFIG=/home/nmanos/automation/ocp-install/nmanos-cluster-a/auth/kubeconfig
netshoot_app_cluster_a=netshoot-58785d5fc7-fzfzg
netshoot_app_cluster_a=netshoot-58785d5fc7-fzfzg
# Connecting from Netshoot pod [netshoot-58785d5fc7-fzfzg] on Cluster A
 # To Nginx service on Cluster B, by its Global IP: 169.254.38.215
/home/nmanos/automation/ocp-install/oc exec netshoot-58785d5fc7-fzfzg -- curl --output /dev/null --max-time 30 --verbose 169.254.38.215
*   Trying 169.254.38.215:80...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 169.254.38.215 (169.254.38.215) port 80 (#0)
> GET / HTTP/1.1
> Host: 169.254.38.215
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.17.8
< Date: Mon, 23 Mar 2020 11:53:03 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 21 Jan 2020 14:39:00 GMT
< Connection: keep-alive
< ETag: "5e270d04-264"
< Accept-Ranges: bytes
< 
{ [612 bytes data]
100   612  100   612    0     0  10736      0 --:--:-- --:--:-- --:--:-- 10736
* Connection #0 to host 169.254.38.215 left intact
/home/nmanos/automation/ocp-install/oc exec netshoot-58785d5fc7-fzfzg -- curl --output /dev/null --max-time 30 --verbose 169.254.38.215
test_clusters_connected_by_service_name
netshoot_app_cluster_a=netshoot-cl-a
nginx_http_cluster_b=nginx-cl-b
nginx_http_cluster_b=nginx-cl-b

🎩︎[2020-03-23 13:53:03]
 ### Testing Service-Discovery: Nginx service will be identified by Domain name: nginx-cl-b ###
 [/home/nmanos/automation/ocp-install]

nginx_http_cluster_b=nginx-cl-b
# Install Ngnix service on OSP Cluster B:
kubconf_b
export KUBECONFIG=/home/nmanos/automation/ocp-install/ocpup/.config/cl1/auth/kubeconfig
/home/nmanos/automation/ocp-install/oc delete deployment nginx-cl-b --ignore-not-found
deployment.extensions "nginx-cl-b" deleted
/home/nmanos/automation/ocp-install/oc create deployment nginx-cl-b --image=nginx
deployment.apps/nginx-cl-b created
/home/nmanos/automation/ocp-install/oc create deployment nginx-cl-b --image=nginx
# Expose Ngnix service on port 80:
/home/nmanos/automation/ocp-install/oc delete service nginx-cl-b --ignore-not-found
service "nginx-cl-b" deleted
/home/nmanos/automation/ocp-install/oc expose deployment nginx-cl-b --port=80 --name=nginx-cl-b
service/nginx-cl-b exposed
/home/nmanos/automation/ocp-install/oc expose deployment nginx-cl-b --port=80 --name=nginx-cl-b
# Wait for Ngnix service to be ready:
/home/nmanos/automation/ocp-install/oc rollout status deployment nginx-cl-b
Waiting for deployment "nginx-cl-b" rollout to finish: 0 of 1 updated replicas are available...
deployment "nginx-cl-b" successfully rolled out
kubconf_a
export KUBECONFIG=/home/nmanos/automation/ocp-install/nmanos-cluster-a/auth/kubeconfig
/home/nmanos/automation/ocp-install/oc run --attach=true --restart=Never --timeout=30s --rm -i --tty --generator=run-pod/v1 netshoot-cl-a --image nicolaka/netshoot -- curl --max-time 20 --verbose nginx-cl-b
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: unable to upgrade connection: container netshoot-cl-a not found in pod netshoot-cl-a_default
* Could not resolve host: nginx-cl-b
* Closing connection 0
curl: (6) Could not resolve host: nginx-cl-b

```

**Comment by sridhargaddam** [comment]
Kubeproxy validation is done in a generic manner now. Closing this issue.
